[package]
name = "once_cell_no_std"
version = "0.1.1"
authors = [
    "Aleksey Kladov <aleksey.kladov@gmail.com>",
    "Philipp Oppermann <dev@phil-opp.com>",
]
license = "MIT OR Apache-2.0"
edition = "2021"
rust-version = "1.81"

description = "Sync single assignment cells for `no_std`"
readme = "README.md"
documentation = "https://docs.rs/once_cell_no_std"

repository = "https://github.com/phil-opp/once_cell_no_std"
keywords = ["no_std", "static", "once", "cell", "sync"]
categories = ["no-std", "rust-patterns", "embedded", "concurrency"]

exclude = ["/.github", "/.devcontainer", "/rustfmt.toml"]

[dev-dependencies]
regex = "1.10.6"

[package.metadata.docs.rs]
rustdoc-args = ["--generate-link-to-definition"]
